#!/bin/sh
EMACSCLIENT="emacsclient"
SERVER_RUNNING=`$EMACSCLIENT -e "(server-running-p)" 2> /dev/null`
if [ -z "$SERVER_RUNNING" ]; then
    unset GTK_IM_MODULE
    unset XMODIFIERS
    exec emacs -mm $@
    exit 0
fi

RUNNING_AS=`$EMACSCLIENT -e "(process-get server-process ':as)"`
OPT=
if [ -z "$EMACS" ]; then
    if [ "$RUNNING_AS" = "gui" -a -z "`echo $TERM | grep xterm`" ]; then
        OPT="-c"
    else
        OPT="-t"
    fi
fi

unset GTK_IM_MODULE
unset XMODIFIERS
exec $EMACSCLIENT $OPT --alternate-editor="emacs" "$@"
