#!/bin/sh

EMACS_CANDIDATES="emacs-25.1 emacs-24.5 emacs-24 emacs"
for candidate in $EMACS_CANDIDATES; do
    for cmd in $(which $candidate); do
        if [ -x "$cmd" ]; then
            unset GTK_IM_MODULE
            unset XMODIFIERS
            exec $cmd $@
            return 0
        fi
    done
done

echo 1>&2 "No emacs command"
return 1
