* .emacs.d

This repository contains the emacs configuration currently I'm using. It is being written to make emacs be fits to my taste but all or some parts of this might be useful to you if you're a C++ developer.

** Prerequisite

 - aspell for flyspell
 - git / mercurial to download packages
 - cscope for ascope and xcscope
 - gnuplot, the graphing utility
 - nodejs / npm for web-beautify
 - markdown for markdown-preview
 - JRE for plantuml
 - texlive (on Ubuntu) for PDF export from org-mode
 - ImageMagick for screenshot
 - The Silver Searcher for AG integration
 - plink (Windows only)

Run following command on Ubuntu:

: $ sudo apt-get install git qt5-qmake cscope gnuplot nodejs-legacy \
:   npm markdown openjdk-7-jre texlive-latex-recommended texlive-latex-extra \
:   texlive-fonts-recommended texlive-base texlive-latex-base imagemagick \
:   silversearcher-ag

*** Emacs and Git version

If you're willing to use emacs 24.4 or later, magit 2.X will be installed and it doesn't work with earlier version of git. You need to install git version 1.9.4 or later. Otherwise, if you're stuck with emacs version 24.3 or earlier, magit 1.X will be installed and the git version will not make a problem.

Now I use version 24.5 only. So you might have problems with this configurations on earlier than 24.5.

*** Compiler

Because I only use gcc for these days, I wrote some stuffs in gcc working manner. If you're using some other compiler something, like getting compiler specific include paths, might not work.

** Installation

Try following commands on your system:

#+BEGIN_SRC shell
$ mv ~/.emacs.d ~/.emacs.d.old # backup your old config
$ git clone git@github.com:zeph1e/.emacs.d.git ~/
#+END_SRC

All of rest packages are installed while launching emacs after that.

** License

Completely free. You may copy whole or part of codes freely to use, to modify, or to redistribute at your own risk.
